language: node_js
deploy:
  provider: pages
  skip_cleanup: true
  github_token: 6ecd652f00c40b53b43ebe46cd669928a4629299
  keep_history: true
  on:
    branch: master
script:
  - npm run eslint:check
  - npm run deploy
